/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ping
         * @description Receive a ping, send a pong
         */
        get: operations["ping"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Health check */
        post: operations["healthCheck"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cms/articles/{moduleId}/{articleId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get article by id */
        get: operations["getArticle"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cms/articles/{moduleId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get articles by module */
        get: operations["getArticles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cms/events/{moduleId}/{eventId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get event by id */
        get: operations["getEvent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cms/events/{moduleId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get events by module */
        get: operations["getEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cms/events/commune/{communeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get events by commune */
        get: operations["getEventsByCommune"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cms/events/commune/{communeId}/{eventId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get event by id and commune */
        get: operations["getEventByCommune"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cms/gallery/{moduleId}/{albumId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get album by id */
        get: operations["getAlbum"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cms/gallery/{moduleId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get albums by module */
        get: operations["getAlbums"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cms/menu-card/{moduleId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get menu card by id */
        get: operations["getMenuCard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cms/addressbook/{moduleId}/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all categories for module */
        get: operations["getCategories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cms/addressbook/{moduleId}/categories/{categoryId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get category by id */
        get: operations["getCategory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cms/addressbook/{moduleId}/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get root entries for module */
        get: operations["getEntries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cms/addressbook/{moduleId}/entries/{entryId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get entry by id */
        get: operations["getEntry"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mailer/message": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send message */
        post: operations["sendMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cms/downloads/{moduleId}/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get categories by module */
        get: operations["getFileDownloadCategories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cms/downloads/{moduleId}/categories/{categoryId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get category by id */
        get: operations["getFileDownloadCategory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cms/downloads/{moduleId}/downloads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get top level downloads by module */
        get: operations["getFileDownloads"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cms/booking-plan/{moduleId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get blocked days */
        get: operations["getBookingPlan"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shop/{moduleId}/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get shop info */
        get: operations["getInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shop/{moduleId}/cart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get cart */
        get: operations["getCart"];
        /** Update cart */
        put: operations["updateCart"];
        post?: never;
        /** Delete cart */
        delete: operations["deleteCart"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shop/{moduleId}/groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get groups */
        get: operations["getGroups"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shop/{moduleId}/groups/{groupId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get group */
        get: operations["getGroup"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shop/{moduleId}/groups/{groupId}/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get products in group */
        get: operations["getGroupProducts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shop/{moduleId}/order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current order */
        get: operations["getOrder"];
        put?: never;
        /** Post order */
        post: operations["postOrder"];
        /** Delete current order */
        delete: operations["deleteOrder"];
        options?: never;
        head?: never;
        /** Update current order */
        patch: operations["updateOrder"];
        trace?: never;
    };
    "/shop/{moduleId}/order/{transactionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get order by transaction id */
        get: operations["getOrderByTransactionId"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shop/{moduleId}/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get products */
        get: operations["getProducts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shop/{moduleId}/products/{productId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get product */
        get: operations["getProduct"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shop/{moduleId}/products/{productId}/group": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get product group */
        get: operations["getProductGroup"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shop/{moduleId}/payment/paypal/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create PayPal order */
        post: operations["createPayPalOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shop/{moduleId}/payment/paypal/capture": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Capture PayPal payment for order */
        post: operations["capturePayPalPaymentForOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Pong */
        Pong: {
            ping: string;
        };
        /** @description API health status */
        HealthStatus: {
            context: string;
            model: {
                name: string;
                datastore: string;
                managed: boolean;
            };
            datastore: {
                id: string;
                status: string;
            };
            user: {
                id: number;
                name: string;
                superuser: boolean;
            };
        };
        /** @description Article */
        Article: {
            id: number;
            module: number;
            slug: string;
            title: string;
            /** Format: date-time */
            date: string;
            teaser: string;
            image?: components["schemas"]["Image"] | null;
            pdf?: components["schemas"]["PDF"] | null;
            /** Format: url */
            website?: string | null;
            author?: string | null;
            content?: components["schemas"]["ArticleParagraph"][];
        };
        /** @description ArticleParagraph */
        ArticleParagraph: {
            id: number;
            title?: string | null;
            text?: string | null;
            image?: components["schemas"]["Image"] | null;
        };
        /** @description Articles */
        Articles: {
            articles: components["schemas"]["Article"][];
            meta: {
                totalCount?: number;
            };
        };
        /** @description Event */
        Event: {
            id: number;
            module: number;
            slug: string;
            title: string;
            teaser?: string;
            description?: string | null;
            address?: string | null;
            /** Format: date-time */
            starts: string;
            /** Format: date-time */
            ends: string;
            image?: components["schemas"]["Image"] | null;
            pdf?: components["schemas"]["PDF"] | null;
            commune?: string | null;
            ticketshopURL?: string | null;
            organizer?: string | null;
            ownerURL?: string | null;
            coordinates?: null | [
                number,
                number
            ];
            flags?: string[];
            tags?: components["schemas"]["Tag"][];
            images?: components["schemas"]["Image"][];
        };
        /** @description Events */
        Events: {
            events: components["schemas"]["Event"][];
            meta: {
                totalCount?: number;
            };
        };
        /** @description Photo Album */
        PhotoAlbum: {
            id: number;
            module: number;
            title: string;
            slug: string;
            images?: components["schemas"]["Image"][];
        };
        /** @description Photo Albums */
        PhotoAlbums: {
            albums: components["schemas"]["PhotoAlbum"][];
            meta: {
                totalCount?: number;
            };
        };
        /** @description Menu card */
        MenuCard: {
            menuCard?: {
                name: string;
                description?: string | null;
                items: {
                    id: number;
                    name: string;
                    description?: string | null;
                    price?: {
                        value?: number;
                        formatted?: string;
                    } | null;
                    image?: components["schemas"]["Image"];
                }[];
            }[];
        };
        /** @description AddressbookEntries */
        AddressbookEntries: {
            entries: components["schemas"]["AddressbookEntry"][];
            meta: {
                totalEntryCount?: number;
            };
        };
        /** @description AddressbookEntry */
        AddressbookEntry: {
            id: number;
            module: number;
            title?: string | null;
            subtitle?: string | null;
            name?: string | null;
            room?: string | null;
            address?: string | null;
            zip?: string | null;
            city?: string | null;
            phone?: string | null;
            mobile?: string | null;
            fax?: string | null;
            /** Format: email */
            email?: string | null;
            /** Format: url */
            web?: string | null;
            description?: string | null;
            priority?: number | null;
            alpha?: string | null;
            image?: components["schemas"]["Image"] | null;
            keywords?: string | null;
            vocabularies?: components["schemas"]["TagsByVocabularies"] | null;
        };
        /** @description Addressbook category */
        AddressbookCategory: {
            id: number;
            module: number;
            priority: number | null;
            title: string | null;
            entries?: (components["schemas"]["AddressbookEntry"] | null)[] | null;
        };
        /** @description Addressbook categories */
        AddressbookCategories: {
            categories: components["schemas"]["AddressbookCategory"][];
            meta: {
                totalCategoryCount?: number;
            };
        };
        /** @description Message request body */
        MailerMessageRequestBody: {
            /** @description Module id */
            "module-id": number;
            /** Format: email */
            email: string;
        } & {
            [key: string]: unknown;
        };
        /** @description FileDownloads */
        FileDownloads: {
            downloads: components["schemas"]["FileDownload"][];
            meta: {
                totalDownloadCount?: number;
            };
        };
        /** @description File Download */
        FileDownload: {
            id: number;
            module: number;
            category?: number;
            title: string;
            number?: string;
            description?: string;
            priority?: number;
            filename: string;
            path: string;
            size: number;
            thumb?: string;
            /** Format: date-time */
            date: string;
            url: string;
            image?: components["schemas"]["Image"];
        };
        /** @description File Download Category */
        FileDownloadCategory: {
            id: number;
            module: number;
            title?: string;
            priority: number;
            downloads?: components["schemas"]["FileDownload"][];
        };
        /** @description File Download Category */
        FileDownloadCategories: {
            categories: components["schemas"]["FileDownloadCategory"][];
            meta: {
                totalCategoryCount: number;
            };
        };
        /** @description Booking plan */
        BookingPlan: {
            module: number;
            blockedDays: string[];
            /** Format: date */
            lastChange: string | null;
        };
        /** @description Preformatted currency value */
        ShopPreformattedNumber: {
            value: number;
            formatted: string;
        };
        /** @description Shop path */
        ShopPath: components["schemas"]["ShopPathItem"][];
        /** @description Shop path item */
        ShopPathItem: {
            id: number;
            name: string;
            slug: string;
        };
        /** @description Info */
        ShopInfo: {
            owner: {
                id: number;
                name: string;
                phone?: string;
                address?: string;
                zip?: string;
                city?: string;
                /** Format: url */
                web?: string;
                /** Format: email */
                email?: string;
            };
            shippingCost: {
                rates: {
                    threshold: number;
                    rate: components["schemas"]["ShopPreformattedNumber"];
                }[];
                freeShippingThreshold: components["schemas"]["ShopPreformattedNumber"];
                unit: string;
                text: string;
            };
            supplementalCost: components["schemas"]["ShopPreformattedNumber"] & {
                description?: string;
            };
        };
        /** @description Cart */
        ShopCart: {
            gross: components["schemas"]["ShopPreformattedNumber"];
            total: components["schemas"]["ShopPreformattedNumber"];
            weight: number;
            products: components["schemas"]["ShopCartProduct"][];
            shipping: {
                price?: components["schemas"]["ShopPreformattedNumber"];
                unit?: string;
            };
            supplementalCost?: components["schemas"]["ShopPreformattedNumber"] & {
                description?: string | null;
            };
        };
        /** @description Cart product */
        ShopCartProduct: {
            product?: components["schemas"]["ShopProduct"];
            quantity?: number;
            weight?: number;
            total?: components["schemas"]["ShopPreformattedNumber"];
        };
        /** @description Cart update request body */
        ShopCartUpdateRequestBody: {
            productId: number;
            quantity: number;
        }[];
        /** @description Product group */
        ShopProductGroup: {
            id?: number;
            path?: components["schemas"]["ShopPath"];
            name?: string | null;
            slug?: string;
            description?: string;
            subgroups?: components["schemas"]["ShopProductGroup"][] | null;
        };
        /** @description Order */
        ShopOrder: {
            /** Format: date */
            date?: string | null;
            transactionId?: components["schemas"]["ShopTransactionId"] | null;
            paymentType?: components["schemas"]["ShopOrderPaymentType"];
            address?: components["schemas"]["ShopOrderAdress"];
            deliveryAddress?: components["schemas"]["ShopOrderDeliveryAdress"] | null;
            message?: string | null;
            total?: components["schemas"]["ShopPreformattedNumber"];
            shippingCost?: components["schemas"]["ShopPreformattedNumber"];
            cart?: {
                price?: components["schemas"]["ShopPreformattedNumber"];
                total?: components["schemas"]["ShopPreformattedNumber"];
                id?: number;
                code?: string;
                name?: string;
                description?: string;
                quantity?: number;
            }[];
        };
        /** @description Patch order request body */
        ShopOrderPatchRequestBody: {
            address?: components["schemas"]["ShopOrderPartialAdress"] | null;
            deliveryAddress?: components["schemas"]["ShopOrderPartialDeliveryAdress"] | null;
            message?: string | null;
        };
        /** @description Address (partial) */
        ShopOrderPartialAdress: {
            company?: string | null;
            salutation?: ("Herr" | "Frau") | null;
            name?: string | null;
            firstname?: string | null;
            address?: string | null;
            zip?: string | null;
            city?: string | null;
            phone?: string | null;
            /** Format: email */
            email?: string | null;
        };
        /** @description Address */
        ShopOrderAdress: WithRequired<components["schemas"]["ShopOrderPartialAdress"], "salutation" | "name" | "firstname" | "address" | "zip" | "city" | "email">;
        /** @description Delivery address (partial) */
        ShopOrderPartialDeliveryAdress: {
            company?: string;
            name?: string;
            address?: string;
            zip?: string;
            city?: string;
            phone?: string;
        };
        /** @description Delivery address */
        ShopOrderDeliveryAdress: WithRequired<components["schemas"]["ShopOrderPartialDeliveryAdress"], "name" | "address" | "zip" | "city">;
        /** @description Transaction id */
        ShopTransactionId: string;
        /**
         * @description Payment type for order
         * @enum {string}
         */
        ShopOrderPaymentType: "paypal" | "prepayment";
        /** @description Product */
        ShopProduct: {
            id: number;
            name?: string | null;
            group?: number | null;
            slug?: string | null;
            code?: string | null;
            ean?: string | null;
            description?: string | null;
            teaser?: string | null;
            legal?: string | null;
            path: components["schemas"]["ShopPath"];
            quantity?: components["schemas"]["ShopPreformattedNumber"] | null;
            weight?: components["schemas"]["ShopPreformattedNumber"] | null;
            price?: components["schemas"]["ShopPreformattedNumber"] | null;
            pricePerUnit?: components["schemas"]["ShopPreformattedNumber"] | null;
            vat?: components["schemas"]["ShopPreformattedNumber"] | null;
            image?: components["schemas"]["Image"] | null;
            pdf?: components["schemas"]["PDF"] | null;
            frontpage?: boolean | null;
        };
        /** @description Create PayPal payment request body */
        ShopPaymentCreateRequestBody: {
            transactionId: string;
        };
        /** @description PayPal payment id */
        ShopPayPalOrderId: string;
        /** @description Image */
        Image: {
            src: string;
            description?: string | null;
            align?: ("left" | "right" | "wide" | "auto") | null;
            srcset?: {
                small?: string;
            } | null;
        };
        /** @description PDF */
        PDF: {
            src: string;
            title?: string;
        };
        /** @description Vocabularies with Tags */
        TagsByVocabularies: components["schemas"]["VocabularyWithTags"][] | null;
        /** @description Vocabulary with tags */
        VocabularyWithTags: {
            id: number;
            name: string;
            description?: string | null;
            tags: components["schemas"]["Tag"][];
        };
        /** @description A taxonomy tag from a vocabulary */
        Tag: {
            id: number;
            name: string;
        };
    };
    responses: never;
    parameters: {
        /** @description Article id */
        articleId: number;
        /** @description Return archived items */
        articleQueryArchived: boolean;
        /** @description Return articles created after given date */
        articleQueryCreatedAfter: string;
        /** @description Return articles created before given date */
        articleQueryCreatedBefore: string;
        /** @description Return given parts (comma separated) */
        articleQueryParts: "content"[];
        /** @description Event id */
        eventId: number;
        /** @description Commune id */
        communeId: string;
        /** @description Return events that end after given date */
        eventQueryEndsAfter: string;
        /** @description Return events that start after given date */
        eventQueryStartsAfter: string;
        /** @description Return events that end before given date */
        eventQueryEndsBefore: string;
        /** @description Return given parts (comma separated) */
        eventQueryParts: ("flags" | "tags" | "images")[];
        /** @description Album id */
        albumId: number;
        /** @description Category id */
        addressbookCategoryId: number;
        /** @description Entry id */
        addressbookEntryId: number;
        /** @description Include given fields (comma separated) */
        addressbookQueryInclude: "entries"[];
        /** @description category id */
        categoryId: number;
        /** @description Include given fields (comma separated) */
        downloadsQueryInclude: "downloads"[];
        /** @description Return days from (including) start of given day */
        bookingPlanQueryFrom: string;
        /** @description Return days before (excluding) start of given day */
        bookingPlanQueryUntil: string;
        /** @description Group id */
        groupId: number;
        /** @description Transaction id */
        transactionId: components["schemas"]["ShopTransactionId"];
        /** @description Product id */
        productId: number;
        /** @description Limit to items selected to be shown on frontpage */
        frontpage: boolean | null;
        /** @description Module id */
        moduleId: number;
        /** @description Return up to given number of items */
        limit: number;
        /** @description Skip given number of items */
        offset: number;
        /** @description Order by property (prepend "-" to reverse order) */
        order: string;
        /** @description Return results recursively */
        recursive: boolean | null;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type SchemaPong = components['schemas']['Pong'];
export type SchemaHealthStatus = components['schemas']['HealthStatus'];
export type SchemaArticle = components['schemas']['Article'];
export type SchemaArticleParagraph = components['schemas']['ArticleParagraph'];
export type SchemaArticles = components['schemas']['Articles'];
export type SchemaEvent = components['schemas']['Event'];
export type SchemaEvents = components['schemas']['Events'];
export type SchemaPhotoAlbum = components['schemas']['PhotoAlbum'];
export type SchemaPhotoAlbums = components['schemas']['PhotoAlbums'];
export type SchemaMenuCard = components['schemas']['MenuCard'];
export type SchemaAddressbookEntries = components['schemas']['AddressbookEntries'];
export type SchemaAddressbookEntry = components['schemas']['AddressbookEntry'];
export type SchemaAddressbookCategory = components['schemas']['AddressbookCategory'];
export type SchemaAddressbookCategories = components['schemas']['AddressbookCategories'];
export type SchemaMailerMessageRequestBody = components['schemas']['MailerMessageRequestBody'];
export type SchemaFileDownloads = components['schemas']['FileDownloads'];
export type SchemaFileDownload = components['schemas']['FileDownload'];
export type SchemaFileDownloadCategory = components['schemas']['FileDownloadCategory'];
export type SchemaFileDownloadCategories = components['schemas']['FileDownloadCategories'];
export type SchemaBookingPlan = components['schemas']['BookingPlan'];
export type SchemaShopPreformattedNumber = components['schemas']['ShopPreformattedNumber'];
export type SchemaShopPath = components['schemas']['ShopPath'];
export type SchemaShopPathItem = components['schemas']['ShopPathItem'];
export type SchemaShopInfo = components['schemas']['ShopInfo'];
export type SchemaShopCart = components['schemas']['ShopCart'];
export type SchemaShopCartProduct = components['schemas']['ShopCartProduct'];
export type SchemaShopCartUpdateRequestBody = components['schemas']['ShopCartUpdateRequestBody'];
export type SchemaShopProductGroup = components['schemas']['ShopProductGroup'];
export type SchemaShopOrder = components['schemas']['ShopOrder'];
export type SchemaShopOrderPatchRequestBody = components['schemas']['ShopOrderPatchRequestBody'];
export type SchemaShopOrderPartialAdress = components['schemas']['ShopOrderPartialAdress'];
export type SchemaShopOrderAdress = components['schemas']['ShopOrderAdress'];
export type SchemaShopOrderPartialDeliveryAdress = components['schemas']['ShopOrderPartialDeliveryAdress'];
export type SchemaShopOrderDeliveryAdress = components['schemas']['ShopOrderDeliveryAdress'];
export type SchemaShopTransactionId = components['schemas']['ShopTransactionId'];
export type SchemaShopOrderPaymentType = components['schemas']['ShopOrderPaymentType'];
export type SchemaShopProduct = components['schemas']['ShopProduct'];
export type SchemaShopPaymentCreateRequestBody = components['schemas']['ShopPaymentCreateRequestBody'];
export type SchemaShopPayPalOrderId = components['schemas']['ShopPayPalOrderId'];
export type SchemaImage = components['schemas']['Image'];
export type SchemaPdf = components['schemas']['PDF'];
export type SchemaTagsByVocabularies = components['schemas']['TagsByVocabularies'];
export type SchemaVocabularyWithTags = components['schemas']['VocabularyWithTags'];
export type SchemaTag = components['schemas']['Tag'];
export type ParameterArticleId = components['parameters']['articleId'];
export type ParameterArticleQueryArchived = components['parameters']['articleQueryArchived'];
export type ParameterArticleQueryCreatedAfter = components['parameters']['articleQueryCreatedAfter'];
export type ParameterArticleQueryCreatedBefore = components['parameters']['articleQueryCreatedBefore'];
export type ParameterArticleQueryParts = components['parameters']['articleQueryParts'];
export type ParameterEventId = components['parameters']['eventId'];
export type ParameterCommuneId = components['parameters']['communeId'];
export type ParameterEventQueryEndsAfter = components['parameters']['eventQueryEndsAfter'];
export type ParameterEventQueryStartsAfter = components['parameters']['eventQueryStartsAfter'];
export type ParameterEventQueryEndsBefore = components['parameters']['eventQueryEndsBefore'];
export type ParameterEventQueryParts = components['parameters']['eventQueryParts'];
export type ParameterAlbumId = components['parameters']['albumId'];
export type ParameterAddressbookCategoryId = components['parameters']['addressbookCategoryId'];
export type ParameterAddressbookEntryId = components['parameters']['addressbookEntryId'];
export type ParameterAddressbookQueryInclude = components['parameters']['addressbookQueryInclude'];
export type ParameterCategoryId = components['parameters']['categoryId'];
export type ParameterDownloadsQueryInclude = components['parameters']['downloadsQueryInclude'];
export type ParameterBookingPlanQueryFrom = components['parameters']['bookingPlanQueryFrom'];
export type ParameterBookingPlanQueryUntil = components['parameters']['bookingPlanQueryUntil'];
export type ParameterGroupId = components['parameters']['groupId'];
export type ParameterTransactionId = components['parameters']['transactionId'];
export type ParameterProductId = components['parameters']['productId'];
export type ParameterFrontpage = components['parameters']['frontpage'];
export type ParameterModuleId = components['parameters']['moduleId'];
export type ParameterLimit = components['parameters']['limit'];
export type ParameterOffset = components['parameters']['offset'];
export type ParameterOrder = components['parameters']['order'];
export type ParameterRecursive = components['parameters']['recursive'];
export type $defs = Record<string, never>;
export interface operations {
    ping: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pong */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pong"];
                };
            };
            /** @description Client error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    healthCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description API health status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
            /** @description Client error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getArticle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Module id */
                moduleId: components["parameters"]["moduleId"];
                /** @description Article id */
                articleId: components["parameters"]["articleId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Article */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        article: components["schemas"]["Article"];
                    };
                };
            };
            /** @description Client error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getArticles: {
        parameters: {
            query?: {
                /** @description Return up to given number of items */
                limit?: components["parameters"]["limit"];
                /** @description Skip given number of items */
                offset?: components["parameters"]["offset"];
                /** @description Order by property (prepend "-" to reverse order) */
                order?: components["parameters"]["order"];
                /** @description Return archived items */
                archived?: components["parameters"]["articleQueryArchived"];
                /** @description Return articles created after given date */
                createdAfter?: components["parameters"]["articleQueryCreatedAfter"];
                /** @description Return articles created before given date */
                createdBefore?: components["parameters"]["articleQueryCreatedBefore"];
                /** @description Return given parts (comma separated) */
                parts?: components["parameters"]["articleQueryParts"];
            };
            header?: never;
            path: {
                /** @description Module id */
                moduleId: components["parameters"]["moduleId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Article */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Articles"];
                };
            };
            /** @description Client error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Module id */
                moduleId: components["parameters"]["moduleId"];
                /** @description Event id */
                eventId: components["parameters"]["eventId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Event */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        event?: components["schemas"]["Event"];
                    };
                };
            };
            /** @description Client error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getEvents: {
        parameters: {
            query?: {
                /** @description Return up to given number of items */
                limit?: components["parameters"]["limit"];
                /** @description Skip given number of items */
                offset?: components["parameters"]["offset"];
                /** @description Order by property (prepend "-" to reverse order) */
                order?: components["parameters"]["order"];
                /** @description Return events that end after given date */
                endsAfter?: components["parameters"]["eventQueryEndsAfter"];
                /** @description Return events that start after given date */
                startsAfter?: components["parameters"]["eventQueryStartsAfter"];
                /** @description Return events that end before given date */
                endsBefore?: components["parameters"]["eventQueryEndsBefore"];
                /** @description Return given parts (comma separated) */
                parts?: components["parameters"]["eventQueryParts"];
            };
            header?: never;
            path: {
                /** @description Module id */
                moduleId: components["parameters"]["moduleId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Event */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Events"];
                };
            };
            /** @description Client error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getEventsByCommune: {
        parameters: {
            query?: {
                /** @description Return up to given number of items */
                limit?: components["parameters"]["limit"];
                /** @description Skip given number of items */
                offset?: components["parameters"]["offset"];
                /** @description Order by property (prepend "-" to reverse order) */
                order?: components["parameters"]["order"];
                /** @description Return events that end after given date */
                endsAfter?: components["parameters"]["eventQueryEndsAfter"];
                /** @description Return events that start after given date */
                startsAfter?: components["parameters"]["eventQueryStartsAfter"];
                /** @description Return events that end before given date */
                endsBefore?: components["parameters"]["eventQueryEndsBefore"];
                /** @description Return given parts (comma separated) */
                parts?: components["parameters"]["eventQueryParts"];
            };
            header?: never;
            path: {
                /** @description Commune id */
                communeId: components["parameters"]["communeId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Event */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Events"];
                };
            };
            /** @description Client error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getEventByCommune: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Commune id */
                communeId: components["parameters"]["communeId"];
                /** @description Event id */
                eventId: components["parameters"]["eventId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Event */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        event?: components["schemas"]["Event"];
                    };
                };
            };
            /** @description Client error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getAlbum: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Module id */
                moduleId: components["parameters"]["moduleId"];
                /** @description Album id */
                albumId: components["parameters"]["albumId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Album */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        album: components["schemas"]["PhotoAlbum"];
                    };
                };
            };
            /** @description Client error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getAlbums: {
        parameters: {
            query?: {
                /** @description Return up to given number of items */
                limit?: components["parameters"]["limit"];
                /** @description Skip given number of items */
                offset?: components["parameters"]["offset"];
                /** @description Order by property (prepend "-" to reverse order) */
                order?: components["parameters"]["order"];
            };
            header?: never;
            path: {
                /** @description Module id */
                moduleId: components["parameters"]["moduleId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Album */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhotoAlbums"];
                };
            };
            /** @description Client error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getMenuCard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Module id */
                moduleId: components["parameters"]["moduleId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Menu card */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MenuCard"];
                };
            };
            /** @description Client error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getCategories: {
        parameters: {
            query?: {
                /** @description Return up to given number of items */
                limit?: components["parameters"]["limit"];
                /** @description Skip given number of items */
                offset?: components["parameters"]["offset"];
                /** @description Order by property (prepend "-" to reverse order) */
                order?: components["parameters"]["order"];
                /** @description Include given fields (comma separated) */
                include?: components["parameters"]["addressbookQueryInclude"];
            };
            header?: never;
            path: {
                /** @description Module id */
                moduleId: components["parameters"]["moduleId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Addressbook category */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AddressbookCategories"];
                };
            };
            /** @description Client error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getCategory: {
        parameters: {
            query?: {
                /** @description Return up to given number of items */
                limit?: components["parameters"]["limit"];
                /** @description Skip given number of items */
                offset?: components["parameters"]["offset"];
                /** @description Order by property (prepend "-" to reverse order) */
                order?: components["parameters"]["order"];
                /** @description Include given fields (comma separated) */
                include?: components["parameters"]["addressbookQueryInclude"];
            };
            header?: never;
            path: {
                /** @description Module id */
                moduleId: components["parameters"]["moduleId"];
                /** @description Category id */
                categoryId: components["parameters"]["addressbookCategoryId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Addressbook category */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        category?: components["schemas"]["AddressbookCategory"];
                        meta?: {
                            totalEntryCount?: number;
                        };
                    };
                };
            };
            /** @description Client error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getEntries: {
        parameters: {
            query?: {
                /** @description Return up to given number of items */
                limit?: components["parameters"]["limit"];
                /** @description Skip given number of items */
                offset?: components["parameters"]["offset"];
                /** @description Order by property (prepend "-" to reverse order) */
                order?: components["parameters"]["order"];
            };
            header?: never;
            path: {
                /** @description Module id */
                moduleId: components["parameters"]["moduleId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Addressbook entries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AddressbookEntries"];
                };
            };
            /** @description Client error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getEntry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Module id */
                moduleId: components["parameters"]["moduleId"];
                /** @description Entry id */
                entryId: components["parameters"]["addressbookEntryId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Addressbook entry */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        entry?: components["schemas"]["AddressbookEntry"];
                    };
                };
            };
            /** @description Client error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    sendMessage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Message data */
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["MailerMessageRequestBody"];
            };
        };
        responses: {
            /** @description Success */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Client error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
            /** @description Server error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getFileDownloadCategories: {
        parameters: {
            query?: {
                /** @description Return up to given number of items */
                limit?: components["parameters"]["limit"];
                /** @description Skip given number of items */
                offset?: components["parameters"]["offset"];
                /** @description Order by property (prepend "-" to reverse order) */
                order?: components["parameters"]["order"];
                /** @description Include given fields (comma separated) */
                include?: components["parameters"]["downloadsQueryInclude"];
            };
            header?: never;
            path: {
                /** @description Module id */
                moduleId: components["parameters"]["moduleId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description category */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileDownloadCategories"];
                };
            };
            /** @description Client error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getFileDownloadCategory: {
        parameters: {
            query?: {
                /** @description Include given fields (comma separated) */
                include?: components["parameters"]["downloadsQueryInclude"];
                /** @description Return up to given number of items */
                limit?: components["parameters"]["limit"];
                /** @description Skip given number of items */
                offset?: components["parameters"]["offset"];
                /** @description Order by property (prepend "-" to reverse order) */
                order?: components["parameters"]["order"];
            };
            header?: never;
            path: {
                /** @description Module id */
                moduleId: components["parameters"]["moduleId"];
                /** @description category id */
                categoryId: components["parameters"]["categoryId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description category */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        category: components["schemas"]["FileDownloadCategory"];
                    };
                };
            };
            /** @description Client error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getFileDownloads: {
        parameters: {
            query?: {
                /** @description Return up to given number of items */
                limit?: components["parameters"]["limit"];
                /** @description Skip given number of items */
                offset?: components["parameters"]["offset"];
                /** @description Order by property (prepend "-" to reverse order) */
                order?: components["parameters"]["order"];
            };
            header?: never;
            path: {
                /** @description Module id */
                moduleId: components["parameters"]["moduleId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description download */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileDownloads"];
                };
            };
            /** @description Client error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getBookingPlan: {
        parameters: {
            query?: {
                /** @description Return days from (including) start of given day */
                from?: components["parameters"]["bookingPlanQueryFrom"];
                /** @description Return days before (excluding) start of given day */
                until?: components["parameters"]["bookingPlanQueryUntil"];
            };
            header?: never;
            path: {
                /** @description Module id */
                moduleId: components["parameters"]["moduleId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Booking plan */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingPlan"];
                };
            };
            /** @description Client error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getInfo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Module id */
                moduleId: components["parameters"]["moduleId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Shop info */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShopInfo"];
                };
            };
            /** @description Client error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getCart: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Module id */
                moduleId: components["parameters"]["moduleId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cart */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShopCart"];
                };
            };
            /** @description Client error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateCart: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Module id */
                moduleId: components["parameters"]["moduleId"];
            };
            cookie?: never;
        };
        /** @description Cart update */
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ShopCartUpdateRequestBody"];
            };
        };
        responses: {
            /** @description Cart */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShopCart"];
                };
            };
            /** @description Client error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteCart: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Module id */
                moduleId: components["parameters"]["moduleId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Client error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getGroups: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Module id */
                moduleId: components["parameters"]["moduleId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cart */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShopProductGroup"][];
                };
            };
            /** @description Client error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Module id */
                moduleId: components["parameters"]["moduleId"];
                /** @description Group id */
                groupId: components["parameters"]["groupId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Group */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShopProductGroup"];
                };
            };
            /** @description Client error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getGroupProducts: {
        parameters: {
            query?: {
                /** @description Return up to given number of items */
                limit?: components["parameters"]["limit"];
                /** @description Return results recursively */
                recursive?: components["parameters"]["recursive"];
            };
            header?: never;
            path: {
                /** @description Module id */
                moduleId: components["parameters"]["moduleId"];
                /** @description Group id */
                groupId: components["parameters"]["groupId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Products in group */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShopProduct"][];
                };
            };
            /** @description Client error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Module id */
                moduleId: components["parameters"]["moduleId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The current order */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShopOrder"];
                };
            };
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Client error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    postOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Module id */
                moduleId: components["parameters"]["moduleId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Order */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        transactionId: components["schemas"]["ShopTransactionId"];
                    };
                };
            };
            /** @description Client error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Module id */
                moduleId: components["parameters"]["moduleId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reset content */
            205: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Client error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Module id */
                moduleId: components["parameters"]["moduleId"];
            };
            cookie?: never;
        };
        /** @description The values to update the order with */
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ShopOrderPatchRequestBody"];
            };
        };
        responses: {
            /** @description The updated order's values */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShopOrder"];
                };
            };
            /** @description Client error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getOrderByTransactionId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Module id */
                moduleId: components["parameters"]["moduleId"];
                /** @description Transaction id */
                transactionId: components["parameters"]["transactionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Order */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShopOrder"];
                };
            };
            /** @description Client error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getProducts: {
        parameters: {
            query?: {
                /** @description Return up to given number of items */
                limit?: components["parameters"]["limit"];
                /** @description Limit to items selected to be shown on frontpage */
                frontpage?: components["parameters"]["frontpage"];
            };
            header?: never;
            path: {
                /** @description Module id */
                moduleId: components["parameters"]["moduleId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Products */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShopProduct"][];
                };
            };
            /** @description Client error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Module id */
                moduleId: components["parameters"]["moduleId"];
                /** @description Product id */
                productId: components["parameters"]["productId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Product */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShopProduct"];
                };
            };
            /** @description Client error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getProductGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Module id */
                moduleId: components["parameters"]["moduleId"];
                /** @description Product id */
                productId: components["parameters"]["productId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Products */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShopProductGroup"];
                };
            };
            /** @description Client error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createPayPalOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Module id */
                moduleId: components["parameters"]["moduleId"];
            };
            cookie?: never;
        };
        /** @description Transaction-ID */
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ShopPaymentCreateRequestBody"];
            };
        };
        responses: {
            /** @description PayPal order created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        orderId: components["schemas"]["ShopPayPalOrderId"];
                    };
                };
            };
            /** @description Client error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    capturePayPalPaymentForOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Module id */
                moduleId: components["parameters"]["moduleId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description PayPal payment for order captured */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShopOrder"];
                };
            };
            /** @description Client error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
type WithRequired<T, K extends keyof T> = T & {
    [P in K]-?: T[P];
};
export enum ApiPaths {
    ping = "/ping",
    healthCheck = "/health",
    getArticle = "/cms/articles/{moduleId}/{articleId}",
    getArticles = "/cms/articles/{moduleId}",
    getEvent = "/cms/events/{moduleId}/{eventId}",
    getEvents = "/cms/events/{moduleId}",
    getEventsByCommune = "/cms/events/commune/{communeId}",
    getEventByCommune = "/cms/events/commune/{communeId}/{eventId}",
    getAlbum = "/cms/gallery/{moduleId}/{albumId}",
    getAlbums = "/cms/gallery/{moduleId}",
    getMenuCard = "/cms/menu-card/{moduleId}",
    getCategories = "/cms/addressbook/{moduleId}/categories",
    getCategory = "/cms/addressbook/{moduleId}/categories/{categoryId}",
    getEntries = "/cms/addressbook/{moduleId}/entries",
    getEntry = "/cms/addressbook/{moduleId}/entries/{entryId}",
    sendMessage = "/mailer/message",
    getFileDownloadCategories = "/cms/downloads/{moduleId}/categories",
    getFileDownloadCategory = "/cms/downloads/{moduleId}/categories/{categoryId}",
    getFileDownloads = "/cms/downloads/{moduleId}/downloads",
    getBookingPlan = "/cms/booking-plan/{moduleId}",
    getInfo = "/shop/{moduleId}/info",
    updateCart = "/shop/{moduleId}/cart",
    getCart = "/shop/{moduleId}/cart",
    deleteCart = "/shop/{moduleId}/cart",
    getGroups = "/shop/{moduleId}/groups",
    getGroup = "/shop/{moduleId}/groups/{groupId}",
    getGroupProducts = "/shop/{moduleId}/groups/{groupId}/products",
    getOrder = "/shop/{moduleId}/order",
    updateOrder = "/shop/{moduleId}/order",
    postOrder = "/shop/{moduleId}/order",
    deleteOrder = "/shop/{moduleId}/order",
    getOrderByTransactionId = "/shop/{moduleId}/order/{transactionId}",
    getProducts = "/shop/{moduleId}/products",
    getProduct = "/shop/{moduleId}/products/{productId}",
    getProductGroup = "/shop/{moduleId}/products/{productId}/group",
    createPayPalOrder = "/shop/{moduleId}/payment/paypal/create",
    capturePayPalPaymentForOrder = "/shop/{moduleId}/payment/paypal/capture"
}
